/**
 * Le Tacos Backend API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { ApiResponseDashboardSummaryResponseDto } from '../model/models';
import { ApiResponseListCategoryBreakdownResponseDto } from '../model/models';
import { ApiResponseListPaymentMethodBreakdownResponseDto } from '../model/models';
import { ApiResponseListPeriodFinancialStatResponseDto } from '../model/models';
import { ApiResponseListTransactionCategoryResponseDto } from '../model/models';
import { ApiResponsePageResponseTransactionCategoryResponseDto } from '../model/models';
import { ApiResponsePageResponseTransactionResponseDto } from '../model/models';
import { ApiResponsePayrollSummaryResponseDto } from '../model/models';
import { ApiResponseTransactionCategoryResponseDto } from '../model/models';
import { ApiResponseTransactionResponseDto } from '../model/models';
import { ApiResponseVoidDto } from '../model/models';
import { PageableDto } from '../model/models';
import { TransactionCategoryRequestDto } from '../model/models';
import { TransactionRequestDto } from '../model/models';

import { Configuration } from '../configuration';

export interface AdminFinanceControllerApiServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @endpoint get /api/admin/transaction-categories/active
   * @param type
   */
  activeCategoriesByType(
    type: 'INCOME' | 'EXPENSE',
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseListTransactionCategoryResponseDto>;

  /**
   *
   *
   * @endpoint get /api/admin/dashboard/by-category
   * @param type
   * @param from
   * @param to
   */
  byCategory(
    type?: 'INCOME' | 'EXPENSE',
    from?: string,
    to?: string,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseListCategoryBreakdownResponseDto>;

  /**
   *
   *
   * @endpoint get /api/admin/transaction-categories
   * @param pageable
   */
  categories(
    pageable: PageableDto,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponsePageResponseTransactionCategoryResponseDto>;

  /**
   *
   *
   * @endpoint post /api/admin/transaction-categories
   * @param transactionCategoryRequestDto
   */
  createCategory(
    transactionCategoryRequestDto: TransactionCategoryRequestDto,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseTransactionCategoryResponseDto>;

  /**
   *
   *
   * @endpoint post /api/admin/transactions
   * @param transactionRequestDto
   */
  createTransaction(
    transactionRequestDto: TransactionRequestDto,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseTransactionResponseDto>;

  /**
   *
   *
   * @endpoint delete /api/admin/transaction-categories/{id}
   * @param id
   */
  deleteCategory(id: string, extraHttpRequestParams?: any): Observable<ApiResponseVoidDto>;

  /**
   *
   *
   * @endpoint delete /api/admin/transactions/{id}
   * @param id
   */
  deleteTransaction(id: string, extraHttpRequestParams?: any): Observable<ApiResponseVoidDto>;

  /**
   *
   *
   * @endpoint get /api/admin/dashboard/monthly
   * @param year
   */
  monthly(
    year: number,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseListPeriodFinancialStatResponseDto>;

  /**
   *
   *
   * @endpoint get /api/admin/dashboard/payment-methods
   * @param type
   * @param from
   * @param to
   */
  paymentMethods(
    type?: 'INCOME' | 'EXPENSE',
    from?: string,
    to?: string,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseListPaymentMethodBreakdownResponseDto>;

  /**
   *
   *
   * @endpoint get /api/admin/dashboard/payroll-summary
   * @param from
   * @param to
   */
  payrollSummary(
    from?: string,
    to?: string,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponsePayrollSummaryResponseDto>;

  /**
   *
   *
   * @endpoint get /api/admin/dashboard/summary
   * @param from
   * @param to
   */
  summary(
    from?: string,
    to?: string,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseDashboardSummaryResponseDto>;

  /**
   *
   *
   * @endpoint get /api/admin/transactions/{id}
   * @param id
   */
  transaction(
    id: string,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseTransactionResponseDto>;

  /**
   *
   *
   * @endpoint get /api/admin/transactions
   * @param pageable
   * @param type
   * @param from
   * @param to
   * @param categoryId
   * @param employeeId
   * @param paymentMethod
   */
  transactions(
    pageable: PageableDto,
    type?: 'INCOME' | 'EXPENSE',
    from?: string,
    to?: string,
    categoryId?: string,
    employeeId?: string,
    paymentMethod?: 'CASH' | 'CARD' | 'WOLT' | 'BANK_TRANSFER' | 'OTHER',
    extraHttpRequestParams?: any,
  ): Observable<ApiResponsePageResponseTransactionResponseDto>;

  /**
   *
   *
   * @endpoint put /api/admin/transaction-categories/{id}
   * @param id
   * @param transactionCategoryRequestDto
   */
  updateCategory(
    id: string,
    transactionCategoryRequestDto: TransactionCategoryRequestDto,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseTransactionCategoryResponseDto>;

  /**
   *
   *
   * @endpoint put /api/admin/transactions/{id}
   * @param id
   * @param transactionRequestDto
   */
  updateTransaction(
    id: string,
    transactionRequestDto: TransactionRequestDto,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseTransactionResponseDto>;

  /**
   *
   *
   * @endpoint get /api/admin/dashboard/weekly
   * @param from
   * @param to
   */
  weekly(
    from?: string,
    to?: string,
    extraHttpRequestParams?: any,
  ): Observable<ApiResponseListPeriodFinancialStatResponseDto>;
}
