/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseEmployeeResponseDto } from '../model/models';
import { ApiResponsePageResponseEmployeeResponseDto } from '../model/models';
import { ApiResponsePageResponsePayrollRecordResponseDto } from '../model/models';
import { ApiResponsePayrollRecordResponseDto } from '../model/models';
import { EmployeeRequestDto } from '../model/models';
import { PageableDto } from '../model/models';
import { PayrollRecordRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminEmployeeControllerApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/admin/employees
     * @param employeeRequestDto 
     */
    createEmployee(employeeRequestDto: EmployeeRequestDto, extraHttpRequestParams?: any): Observable<ApiResponseEmployeeResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/admin/employees/{employeeId}/payroll
     * @param employeeId 
     * @param payrollRecordRequestDto 
     */
    createPayrollRecord(employeeId: string, payrollRecordRequestDto: PayrollRecordRequestDto, extraHttpRequestParams?: any): Observable<ApiResponsePayrollRecordResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/admin/employees/{id}
     * @param id 
     */
    deleteEmployee(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint delete /api/admin/employees/payroll-records/{payrollRecordId}
     * @param payrollRecordId 
     */
    deletePayrollRecord(payrollRecordId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/admin/employees/{id}
     * @param id 
     */
    employee(id: string, extraHttpRequestParams?: any): Observable<ApiResponseEmployeeResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/admin/employees
     * @param pageable 
     */
    employees(pageable: PageableDto, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseEmployeeResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/admin/employees/{employeeId}/payroll
     * @param employeeId 
     * @param pageable 
     */
    payrollRecords(employeeId: string, pageable: PageableDto, extraHttpRequestParams?: any): Observable<ApiResponsePageResponsePayrollRecordResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/employees/{id}
     * @param id 
     * @param employeeRequestDto 
     */
    updateEmployee(id: string, employeeRequestDto: EmployeeRequestDto, extraHttpRequestParams?: any): Observable<ApiResponseEmployeeResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/employees/payroll-records/{payrollRecordId}
     * @param payrollRecordId 
     * @param payrollRecordRequestDto 
     */
    updatePayrollRecord(payrollRecordId: string, payrollRecordRequestDto: PayrollRecordRequestDto, extraHttpRequestParams?: any): Observable<ApiResponsePayrollRecordResponseDto>;

}
