/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseAdminCategoryResponseDto } from '../model/models';
import { ApiResponseAdminMediaAssetResponseDto } from '../model/models';
import { ApiResponseAdminMenuItemResponseDto } from '../model/models';
import { ApiResponsePageResponseAdminCategoryResponseDto } from '../model/models';
import { ApiResponsePageResponseAdminMenuItemResponseDto } from '../model/models';
import { CategoryRequestDto } from '../model/models';
import { MediaAssetOrderRequestDto } from '../model/models';
import { MediaAssetUpdateRequestDto } from '../model/models';
import { MenuItemRequestDto } from '../model/models';
import { PageableDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminMenuControllerApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/admin/categories
     * @param pageable 
     */
    categories1(pageable: PageableDto, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseAdminCategoryResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/admin/categories
     * @param categoryRequestDto 
     */
    createCategory1(categoryRequestDto: CategoryRequestDto, extraHttpRequestParams?: any): Observable<ApiResponseAdminCategoryResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/admin/menu-items
     * @param menuItemRequestDto 
     */
    createMenuItem(menuItemRequestDto: MenuItemRequestDto, extraHttpRequestParams?: any): Observable<ApiResponseAdminMenuItemResponseDto>;

    /**
     * 
     * 
     * @endpoint delete /api/admin/categories/{id}
     * @param id 
     */
    deleteCategory1(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint delete /api/admin/menu-items/{menuItemId}/images/{imageId}
     * @param menuItemId 
     * @param imageId 
     */
    deleteImage(menuItemId: string, imageId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint delete /api/admin/menu-items/{id}
     * @param id 
     */
    deleteMenuItem(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/admin/menu-items
     * @param pageable 
     */
    menuItems(pageable: PageableDto, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseAdminMenuItemResponseDto>;

    /**
     * 
     * 
     * @endpoint patch /api/admin/menu-items/{menuItemId}/images/reorder
     * @param menuItemId 
     * @param mediaAssetOrderRequestDto 
     */
    reorderImages(menuItemId: string, mediaAssetOrderRequestDto: Array<MediaAssetOrderRequestDto>, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint patch /api/admin/menu-items/{menuItemId}/images/{imageId}/primary
     * @param menuItemId 
     * @param imageId 
     */
    setPrimaryImage(menuItemId: string, imageId: string, extraHttpRequestParams?: any): Observable<ApiResponseAdminMediaAssetResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/categories/{id}
     * @param id 
     * @param categoryRequestDto 
     */
    updateCategory1(id: string, categoryRequestDto: CategoryRequestDto, extraHttpRequestParams?: any): Observable<ApiResponseAdminCategoryResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/menu-items/{menuItemId}/images/{imageId}
     * @param menuItemId 
     * @param imageId 
     * @param mediaAssetUpdateRequestDto 
     */
    updateImage(menuItemId: string, imageId: string, mediaAssetUpdateRequestDto: MediaAssetUpdateRequestDto, extraHttpRequestParams?: any): Observable<ApiResponseAdminMediaAssetResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/admin/menu-items/{id}
     * @param id 
     * @param menuItemRequestDto 
     */
    updateMenuItem(id: string, menuItemRequestDto: MenuItemRequestDto, extraHttpRequestParams?: any): Observable<ApiResponseAdminMenuItemResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/admin/menu-items/{menuItemId}/images
     * @param menuItemId 
     * @param file 
     * @param altEn 
     * @param altRo 
     * @param primary 
     */
    uploadImage(menuItemId: string, file: Blob, altEn?: string, altRo?: string, primary?: boolean, extraHttpRequestParams?: any): Observable<ApiResponseAdminMediaAssetResponseDto>;

}
