/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseAdminMeResponseDto } from '../model/models';
import { ApiResponseAuthResponseDto } from '../model/models';
import { ChangePasswordRequestDto } from '../model/models';
import { LoginRequestDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthControllerApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/auth/change-password
     * @param changePasswordRequestDto 
     */
    changePassword(changePasswordRequestDto: ChangePasswordRequestDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/auth/login
     * @param loginRequestDto 
     */
    login(loginRequestDto: LoginRequestDto, extraHttpRequestParams?: any): Observable<ApiResponseAuthResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/auth/logout
     * @param leTacosRefresh 
     */
    logout(leTacosRefresh?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/auth/me
     */
    me(extraHttpRequestParams?: any): Observable<ApiResponseAdminMeResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/auth/refresh
     * @param leTacosRefresh 
     */
    refresh(leTacosRefresh?: string, extraHttpRequestParams?: any): Observable<ApiResponseAuthResponseDto>;

}
