/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListPublicCategoryResponseDto } from '../model/models';
import { ApiResponseListPublicMenuItemResponseDto } from '../model/models';
import { ApiResponsePublicMenuResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PublicMenuControllerApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/public/categories
     * @param locale 
     * @param acceptLanguage 
     */
    categories2(locale?: string, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<ApiResponseListPublicCategoryResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/public/menu
     * @param locale 
     * @param acceptLanguage 
     */
    menu(locale?: string, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<ApiResponsePublicMenuResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/public/menu-items
     * @param locale 
     * @param acceptLanguage 
     */
    menuItems1(locale?: string, acceptLanguage?: string, extraHttpRequestParams?: any): Observable<ApiResponseListPublicMenuItemResponseDto>;

}
