/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminCategoryResponseDto { 
    id?: string;
    nameEn?: string;
    nameRo?: string;
    markAsNew?: boolean;
    active?: boolean;
    displayOrder?: number;
}

