/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminMediaAssetResponseDto { 
    id?: string;
    publicId?: string;
    secureUrl?: string;
    resourceType?: string;
    format?: string;
    width?: number;
    height?: number;
    bytes?: number;
    version?: string;
    folder?: string;
    alt?: string;
    primary?: boolean;
    displayOrder?: number;
}

