/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminMediaAssetResponseDto } from './adminMediaAssetResponse';


export interface AdminMenuItemResponseDto { 
    id?: string;
    categoryId?: string;
    categoryNameEn?: string;
    nameEn?: string;
    nameRo?: string;
    descriptionEn?: string;
    descriptionRo?: string;
    price?: number;
    currency?: string;
    weightLabel?: string;
    markAsNew?: boolean;
    popular?: boolean;
    active?: boolean;
    displayOrder?: number;
    images?: Array<AdminMediaAssetResponseDto>;
}

