/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiResponseVoidDto { 
    success?: boolean;
    status?: number;
    message?: string;
    data?: any | null;
    errors?: { [key: string]: string; };
    timestamp?: string;
}

