/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicMenuResponseDto } from './publicMenuResponse';


export interface ApiResponsePublicMenuResponseDto { 
    success?: boolean;
    status?: number;
    message?: string;
    data?: PublicMenuResponseDto;
    errors?: { [key: string]: string; };
    timestamp?: string;
}

