/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminMenuItemResponseDto } from './adminMenuItemResponse';


export interface ApiResponseAdminMenuItemResponseDto { 
    success?: boolean;
    status?: number;
    message?: string;
    data?: AdminMenuItemResponseDto;
    errors?: { [key: string]: string; };
    timestamp?: string;
}

