/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryBreakdownResponseDto } from './categoryBreakdownResponse';


export interface ApiResponseListCategoryBreakdownResponseDto { 
    success?: boolean;
    status?: number;
    message?: string;
    data?: Array<CategoryBreakdownResponseDto>;
    errors?: { [key: string]: string; };
    timestamp?: string;
}

