/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentMethodBreakdownResponseDto } from './paymentMethodBreakdownResponse';


export interface ApiResponseListPaymentMethodBreakdownResponseDto { 
    success?: boolean;
    status?: number;
    message?: string;
    data?: Array<PaymentMethodBreakdownResponseDto>;
    errors?: { [key: string]: string; };
    timestamp?: string;
}

