/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CategoryBreakdownResponseDto { 
    categoryId?: string;
    categoryName?: string;
    type?: CategoryBreakdownResponseDto.TypeEnum;
    total?: number;
}
export namespace CategoryBreakdownResponseDto {
    export const TypeEnum = {
        Income: 'INCOME',
        Expense: 'EXPENSE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


