/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DashboardSummaryResponseDto { 
    from?: string;
    to?: string;
    totalIncome?: number;
    totalExpenses?: number;
    netProfit?: number;
}

