/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MenuItemRequestDto { 
    categoryId: string;
    nameEn: string;
    nameRo: string;
    descriptionEn?: string;
    descriptionRo?: string;
    price: number;
    weightLabel?: string;
    markAsNew?: boolean;
    popular?: boolean;
    active?: boolean;
    displayOrder: number;
}

