/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminMenuItemResponseDto } from './adminMenuItemResponse';


export interface PageResponseAdminMenuItemResponseDto { 
    content?: Array<AdminMenuItemResponseDto>;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
    first?: boolean;
    last?: boolean;
}

