/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionCategoryResponseDto } from './transactionCategoryResponse';


export interface PageResponseTransactionCategoryResponseDto { 
    content?: Array<TransactionCategoryResponseDto>;
    page?: number;
    size?: number;
    totalElements?: number;
    totalPages?: number;
    first?: boolean;
    last?: boolean;
}

