/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PeriodFinancialStatResponseDto { 
    period?: string;
    income?: number;
    expenses?: number;
    netProfit?: number;
}

