/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicMenuCategoryGroupResponseDto } from './publicMenuCategoryGroupResponse';


export interface PublicMenuResponseDto { 
    categories?: Array<PublicMenuCategoryGroupResponseDto>;
}

