/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicMediaAssetResponseDto } from './publicMediaAssetResponse';


export interface PublicMenuItemResponseDto { 
    id?: string;
    name?: string;
    description?: string;
    price?: number;
    currency?: string;
    weightLabel?: string;
    markAsNew?: boolean;
    popular?: boolean;
    categoryId?: string;
    categoryName?: string;
    images?: Array<PublicMediaAssetResponseDto>;
}

