/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublicCategoryResponseDto { 
    id?: string;
    name?: string;
    markAsNew?: boolean;
    displayOrder?: number;
}

