/**
 * Le Tacos Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionResponseDto { 
    id?: string;
    type?: TransactionResponseDto.TypeEnum;
    amount?: number;
    currency?: string;
    transactionDate?: string;
    categoryId?: string;
    categoryName?: string;
    paymentMethod?: TransactionResponseDto.PaymentMethodEnum;
    notes?: string;
    employeeId?: string;
    employeeName?: string;
    menuItemId?: string;
    menuItemNameEn?: string;
    payrollRecordId?: string;
}
export namespace TransactionResponseDto {
    export const TypeEnum = {
        Income: 'INCOME',
        Expense: 'EXPENSE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const PaymentMethodEnum = {
        Cash: 'CASH',
        Card: 'CARD',
        Wolt: 'WOLT',
        BankTransfer: 'BANK_TRANSFER',
        Other: 'OTHER'
    } as const;
    export type PaymentMethodEnum = typeof PaymentMethodEnum[keyof typeof PaymentMethodEnum];
}


